src/Entity/Promo.php
<?php

namespace App\Entity;

use App\Repository\PromoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PromoRepository::class)
 */
class Promo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
    
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cover Template · Bootstrap</title>

    <!-- Bootstrap core CSS -->
    {{encore_entry_link_tags('app') }}

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.scss" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
      <a class="nav-link active" href="/">
    <img class="nav-link active" href="/" style="width: 250px; margin-left: 600px;" src="https://d21buns5ku92am.cloudfront.net/66697/images/244718-dealabs-logo_for_campaigns-81ef02-large-1493191392.png" alt="logo"/> 
      </a>
    <div class="inner">
      <nav class="nav nav-masthead justify-content-center">
      
        <li class="nav-item">
        <li class="nav-item">
        {% if is_granted('ROLE_ADMIN') %}
          <a class="nav-link" href="{{ path('affichage_promo') }}">Promo code</a>
        </li>
          <a class="nav-link" href="{{ path('article_new') }}">Create a good plan</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ path('promo_new') }}">Create promo code</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/utilisateurs">Espace Admin</a>
        </li>
        {% endif %}
        <a class="nav-link" href="#"></a>
          {% if app.user %}
   <a href="{{ path('app_logout') }}" class="btn btn-danger" style="margin: 0;">Logout</a>
  {% else %}
   <a href="{{ path('app_login') }}" class="btn btn-primary" style="margin: 0;">Login</a>
  {% endif %}
    {% if not app.user %}<a href="{{ path('app_register') }}" class="btn btn-primary" style="margin: 0;">Register</a>{% endif %}
      </nav>
    </div>
  </header>



  <footer class="mastfoot mt-auto">
  </footer>
</div>

{{encore_entry_script_tags('app') }}
</body>
</html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Bienvenue sur dealabs!{% endblock %}</title>
        {% block stylesheets %}{{encore_entry_link_tags('app') }}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{{encore_entry_script_tags('app') }}{% endblock %}
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}

    <main role="main" class="container">

    <div class="row">
     {% for article in articles %}
    
    

        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <img src="{{ article.image }}" alt="{{ article.image }}">
            <div class="card-body">
              <p class="card-text"> {{ article.description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ path('article_show', {"id":article.id}) }}" class="btn btn-sm btn-outline-secondary">View</a>
                  {% if is_granted('ROLE_ADMIN') %}
                  <a href="{{ path('article_edit', {"id":article.id}) }}" class="btn btn-sm btn-outline-secondary">Edit</a>
                  <a href="{{ path('article_delete', {"id": article.id}) }}" class="btn btn-sm btn-outline-secondary" onclick="return confirm('Attention ce ci va supprimer l\'article selectionner')">Delete</a>
                  {% endif %}
                </div>
                <small class="text-muted">{{ article.createdAt |date("d/m/Y") }}</small>
              </div>
            </div>
          </div>
        </div>
        
{% endfor %}

{% endblock %}